### ISSUE TITLE
Create Web page

### ISSUE THREAD

**Issue by IneshV** [IneshV/Comp333final#4]
Allow users to upload voice recordings and desired pdfs to read.

**Comment by IneshV** [comment]
If time allows, I would like to implement this in an IOS app using Xcode

**Comment by IneshV** [comment]
First Commit:  We were able to make an HTML and javascript file to view pdfs.  Although we did not code unit test, we tried several pdfs and the site was able to handle and preview them.  A successful unit test of this site is to be able to upload and view a pdf.

**Comment by soroberts** [comment]
Not a traditional unit test, but this is a reasonable "user" test!
