### ISSUE TITLE
Develop Web page

### ISSUE THREAD

**Issue by IneshV** [IneshV/Comp333final#7]
We would like our web page to have a comprehensive user interface with features such as the ability to select parts of the text to be read aloud

**Comment by IneshV** [comment]
2nd Commit:  For this commit I spent a majority of time trying to properly parse the pdf to add the functionality to capture user selected text.  However, it was not able to be done successfully.  I was able to add a style file and am relatively happy with the UI.  I am closing this issue since the ability to select parts of the text to be read aloud is in a different issue

**Comment by soroberts** [comment]
@MilesM326 @IneshV It's not clear to me how this relates to a user or unit test but there was a clear effort to communicate what you want me to look at for this commit which I do appreciate, so -1 pt rather than -2
